wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0301.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0302.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0303.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0304.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0305.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0306.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0307.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0308.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0309.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0310.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0311.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0312.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0313.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0314.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0315.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0316.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0317.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0318.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0319.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0320.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0321.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0322.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0323.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0324.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0325.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0326.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0327.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0328.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0329.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0330.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0331.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0332.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0333.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0334.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0335.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0336.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0337.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0338.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0339.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0340.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0341.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0342.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0343.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0344.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0345.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0346.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0347.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0348.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0349.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0350.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0351.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0352.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0353.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0354.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0355.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0356.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0357.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0358.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0359.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0360.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0361.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0362.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0363.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0364.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0365.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0366.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0367.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0368.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0369.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0370.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0371.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0372.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0373.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0374.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0375.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0376.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0377.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0378.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0379.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0380.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0381.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0382.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0383.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0384.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0385.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0386.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0387.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0388.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0389.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0390.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0391.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0392.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0393.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0394.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0395.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0396.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0397.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0398.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0399.xml.gz
wget ftp://ftp.ncbi.nlm.nih.gov/pubmed/baseline/pubmed19n0400.xml.gz
